@url = http://localhost:3001/api/blogs
@blogId = 1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdGVzdC50ZXN0IiwiaWQiOjEsImlhdCI6MTY1OTU0MjU2MX0.MB8r4lcLjfYW_xkebGwO0T-RGKiwQMBVWSxGkU0CcLM

## Get all blogs
GET {{url}}

### Get all blogs with query parameter
GET {{url}}?search=react

### Get a blog
GET {{url}}/{{blogId}}

### Create new blog
POST {{url}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "this is React, okay!",
    "author": "asd",
    "url": "String",
    "likes": 1,
    "year": 2022
}

### Creating an invalid blog
POST {{url}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "String",
    "url": "String",
    "likes": 1
}

### Delete a blog
DELETE {{url}}/{{blogId}}
Authorization: bearer {{token}}

### Like a blog
PUT {{url}}/{{blogId}}
Content-Type: application/json

{
    "likes": 10
}

### Invalid like
PUT {{url}}/{{blogId}}
Content-Type: application/json

{
    "likes": -10
}
