@url = http://localhost:3001/api/blogs
@blogId = 13
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdGVzdC50ZXN0IiwiaWQiOjcsImlhdCI6MTY1OTUxNjExOX0.8raEXMeqYsctSk_hYgyiy4dZlsNWuDJOmX749uVbNzU

## Get all blogs
GET {{url}}

### Get a blog
GET {{url}}/{{blogId}}

### Create new blog
POST {{url}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "NEW",
    "author": "String",
    "url": "String",
    "likes": 1
}

### Creating an invalid blog
POST {{url}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "title": "String",
    "url": "String",
    "likes": 1
}

### Delete a blog
DELETE {{url}}/{{blogId}}
Authorization: bearer {{token}}

### Like a blog
PUT {{url}}/{{blogId}}
Content-Type: application/json

{
    "likes": 10
}

### Invalid like
PUT {{url}}/{{blogId}}
Content-Type: application/json

{
    "likes": -10
}
