@url = http://localhost:3001/api/blogs
@blogId = 3

## Get all blogs
GET {{url}}

### Get a blog
GET {{url}}/{{blogId}}

### Create new blog
POST {{url}}
Content-Type: application/json

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 1
}

### Delete a blog
DELETE {{url}}/{{blogId}}

### Like a blog
PUT {{url}}/{{blogId}}
Content-Type: application/json

{
    "likes": 10
}

### Invalid like
PUT {{url}}/{{blogId}}
Content-Type: application/json

{
    "likes": -10
}
