@url = http://localhost:3001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlcjEiLCJpZCI6NSwiaWF0IjoxNjU5NTExMzg1fQ.iTo5KTn2uTA9gH4pjhkynm8DAEqQfndJg58ZlXf-9qg

## Get all
GET {{url}}/users

### Create new
POST {{url}}/users
Content-Type: application/json

{
    "username": "tester1",
    "name": "String",
    "password": "assdasd"
}

### Update name

PUT {{url}}/users/tester1
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": "The tester"
}


### Login

POST {{url}}/login
Content-Type: application/json

{
    "username": "tester1",
    "password": "assdasd"
}