@url = http://localhost:3001/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdGVzdC50ZXN0IiwiaWQiOjEsImlhdCI6MTY1OTUzMjM3NX0.eVajzyy875Z5BSIrpyMpNqKRzosIDJWCJcjZYmliDbU
@id = 1

### Get all
GET {{url}}/users

### Get one
GET {{url}}/users/{{id}}

### Get one, only show readings that are unread
GET {{url}}/users/{{id}}?read=false

### Create new
POST {{url}}/users
Content-Type: application/json

{
    "username": "test@test.test",
    "name": "String",
    "password": "assdasd"
}

### Update name
PUT {{url}}/users/test@test.test
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name": "The tester 123"
}


### Login
POST {{url}}/login
Content-Type: application/json

{
    "username": "test@test.test",
    "password": "assdasd"
}